#!/bin/bash
# Sign a pdf
# https://gist.github.com/chrpinedo/a2a2af757e96aec0d6f69d707629a01a
# https://superuser.com/questions/452759/how-to-add-a-picture-onto-an-existing-pdf-file

# signpdf -document Doc.pdf -offset "-10cm -10cm" -page 1 -n Doc_signed.pdf

signature=~/documents/signature.pdf
suffix='_signed'

echo "Signing your document..."

while getopts d:o:p:n: option
do
    case "${option}"
        in
        d) DOCUMENT=${OPTARG};;
        o) OFFSET=${OPTARG};;
        p) PAGE=${OPTARG};;
        n) NAME=${OPTARG};;
    esac
done

# Create the template signature page
echo "- Creating template..."
pdfjam --paper 'a4paper' --scale 0.3 --offset '+3cm -11cm' --outfile _stamp.pdf $signature > /dev/null 2>&1

# Create blank A4 page
echo "- Creating blank pages..."
convert xc:none -page A4 _blank.pdf

# Add the blank page to the template
echo "- Finishing template..."
pdftk A=_stamp.pdf B=_blank.pdf cat B1 A1 output _multistamp.pdf

# Join the original document with the template
echo "- Joining documents..."
filename="${DOCUMENT%.*}"
pdftk $DOCUMENT multistamp _multistamp.pdf output $filename"_signed.pdf"

echo "Removing temp files..."
rm "_blank.pdf"
rm "_stamp.pdf"
rm "_multistamp.pdf"
echo "Document signed. Have a good day."
