#!/usr/bin/bash
#eval "export $(egrep -z DBUS_SESSION_BUS_ADDRESS /proc/$(pgrep -u $LOGNAME gnome-session)/environ)";
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
#TODO: Move to ~/.locale./share/sounds
sound="/usr/share/sounds/freedesktop/stereo/message-new-instant.oga"
/usr/bin/notify-send "Take a Break!" "You've done great!"
/usr/bin/mplayer $sound 
