#!/bin/bash
PIDFILE="/var/run/user/$UID/bg.pid"
declare -a PIDs

_screen() {
	xwinwrap -b -s -fs -st -sp -nf -ov -fdt \
		-- mpv -wid WID \
		--really-quiet --framedrop=vo \
		--no-audio --panscan="1.0" \
		"$2" &
	PIDs+=($!)
}

while read p; do
	[[ $(ps -p "$p" -o comm=) == "xwinwrap" ]] && kill -9 "$p";
done < $PIDFILE

_screen "$i" "$1"

#for i in $( xrandr -q | grep ' connected' | grep -oP '\d+x\d+\+\d+\+\d+')
#do
#	_screen "$i" "$1"
#done

printf "%s\n" "${PIDs[@]}" > $PIDFILE
