#!/bin/sh

# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin/scripts":$PATH
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.emacs.d/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
export PATH=$HOME/.config/nvcode/utils/bin:$PATH
# Get color support for 'less'
export LESS="--RAW-CONTROL-CHARS"
